fix: #1936 - When reset zoom, click room/user on sidebar display white screen
RocketChat/Rocket.Chat.Electron pull request #1947
Opened 2021-01-08 03:31 UTC by vuongtaquoc

Closes #1936

It happens with webview. I fixed it by just zooming for webview content.

2021-01-08 03:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Electron?pullRequest=1947) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Electron?pullRequest=1947) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Electron?pullRequest=1947) it.</sub>

2021-09-13 14:59 UTC, ggazzo requested changes

2021-09-13 14:59 UTC, ggazzo commented on src/ui/main/menuBar.ts
> +            if (zoomLevel && zoomLevel >= 9) {
```suggestion
            if (!Number.isInteger(zoomLevel) || zoomLevel >= 9) {
```

2021-09-13 14:59 UTC, ggazzo commented on src/ui/main/menuBar.ts
> +              guestWebContents?.setZoomLevel(zoomLevel + 1);
```suggestion
            guestWebContents?.setZoomLevel(zoomLevel + 1);
```

2021-09-13 15:12 UTC, cazetto commented on src/ui/main/menuBar.ts
> +            if (zoomLevel && zoomLevel >= 9) {
isNan?

2021-09-14 02:59 UTC, ggazzo approved these changes

2021-09-14 03:01 UTC, merged