Feat/settings
RocketChat/Rocket.Chat.Electron pull request #2138
Opened 2021-08-31 12:16 UTC by cazetto

Add Settings Page

2021-09-02 13:32 UTC, ggazzo commented on src/ui/components/SettingsView/features/BugsnagOptIn.tsx
> +  };
useCallback

2021-09-02 14:42 UTC, ggazzo requested changes

2021-09-02 14:42 UTC, ggazzo commented on src/app/main/app.ts
> +  // @TODO - Can I remove this line?
try just disable/enable instead of relaunch

remove console.log

2021-09-02 17:56 UTC, cazetto commented on src/ui/main/menuBar.ts
> +        accelerator: 'CommandOrControl+P',
What about cmd+i ?

2021-09-03 09:48 UTC, cazetto commented on src/app/main/persistence.ts
> +export const getElectronStore = (): ElectronStore<PersistableValues> => {
stop exporting getElectronStore

2021-09-03 09:48 UTC, cazetto commented on src/preload.ts
> +  // setupRendererErrorHandling('webviewPreload');
is it common sense that this is going to be removed?

2021-09-03 09:48 UTC, cazetto commented on src/ui/components/SettingsView/features/BugsnagOptIn.tsx
> +export const BugsnagOptIn: FC = () => {
Isn't it better to be called BugsnagOpt?

2021-09-03 19:59 UTC, ggazzo approved these changes

2021-09-03 20:00 UTC, merged