feat: toggle dock bounce added for OSX alerts
RocketChat/Rocket.Chat.Electron pull request #2465
Opened 2022-08-10 04:58 UTC by Palanikannan1437

Closes Issue #2463

## Issue in brief
User was not able to toggle off Dock Bounce in OSX platform for badge alerts, since `Flash Frame` is not an OSX specific feature which was specified in the settings earlier.

## Suggested Fixes/Changes
1. `Enable Flash Frame` toggle changed to `Toggle Dock Bounce on alert` and the description is changed accordingly
2. Added a constraint for `Flash Frame` for OSX, since `Flash Frame` is not an OSX specific feature

## Suggested Settings window on OSX:
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/73993394/183819309-0c9ec346-6fd0-4d84-b486-6fca222a51e1.png">

2022-08-10 17:01 UTC, Palanikannan1437 commented
@jeanfbrito It'd be awesome if you could review these changes and let me know if I need to make any more changes to my PR

2022-08-15 15:15 UTC, jeanfbrito commented
Nice contribution @Palanikannan1437. We will merge it soon. Please take a look on the review. Just a simple thing.

2022-08-15 15:59 UTC, Palanikannan1437 commented
> Nice contribution @Palanikannan1437. We will merge it soon. Please take a look on the review. Just a simple thing.

Hey there!! Thank you so much @jeanfbrito, I am not able to see any reviews yet on GitHub though.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/73993394/184670645-1457cf63-83f8-40cf-a833-0d74b23add0a.png">

This is what you meant by reviews right, or did I misunderstand you?

2022-08-15 16:03 UTC, jeanfbrito requested changes

2022-08-15 16:04 UTC, jeanfbrito commented
I forgot to publish it. Now is showing.

2022-08-15 16:23 UTC, Palanikannan1437 commented on src/i18n/en.i18n.json
> +        "descriptionOSX": "Bounces the app icon in the dock to attract user's attention."
Ohh yeah!! That makes a lot of sense, I've made the changes!

2022-08-15 16:34 UTC, jeanfbrito approved these changes

2022-08-15 16:54 UTC, merged